project_id = "uxttihjsxfowursjyult"

[functions.admin-manage-admins]
verify_jwt = false

[functions.mercadopago-webhook]
verify_jwt = false

[functions.facebook-leads-webhook]
verify_jwt = false

[functions.facebook-subscribe-webhook]
verify_jwt = false

[functions.facebook-list-lead-forms]
verify_jwt = false

[functions.facebook-oauth-callback]
verify_jwt = false

[functions.facebook-oauth-initiate]
verify_jwt = false

[functions.form-webhook]
verify_jwt = false

[functions.whatsapp-message-webhook]
verify_jwt = false

[functions.whatsapp-qr-webhook]
verify_jwt = false

[functions.whatsapp-status-webhook]
verify_jwt = false

[functions.fetch-ads-insights]
verify_jwt = false

[functions.fetch-campaign-ads]
verify_jwt = false

[functions.add-organization-member]
verify_jwt = false

[functions.admin-delete-user]
verify_jwt = false

[functions.facebook-switch-page]
verify_jwt = false

[functions.set-whatsapp-presence]
verify_jwt = false

[functions.fetch-presence-status]
verify_jwt = false

[functions.send-whatsapp-message]
verify_jwt = false

[functions.send-whatsapp-media]
verify_jwt = false

[functions.check-whatsapp-status]
verify_jwt = false

[functions.create-whatsapp-instance]
verify_jwt = false

[functions.delete-whatsapp-instance]
verify_jwt = false

[functions.disconnect-whatsapp-instance]
verify_jwt = false

[functions.send-whatsapp-reaction]
verify_jwt = false
