/**
 * URL reachable by browsers and third-party webhook/OAuth providers.
 *
 * Managed Supabase exposes SUPABASE_URL publicly. In the official self-hosted
 * stack SUPABASE_URL is intentionally internal (http://api-gw:8000), while
 * SUPABASE_PUBLIC_URL is the external HTTPS origin. Keep the fallback so the
 * same function sources continue to work on the managed platform.
 */
function parseHttpUrl(value: string, label: string): URL {
  let parsed: URL;

  try {
    parsed = new URL(value);
  } catch {
    throw new Error(`${label} is not a valid absolute URL`);
  }

  if (parsed.protocol !== 'http:' && parsed.protocol !== 'https:') {
    throw new Error(`${label} must use http:// or https://`);
  }

  return parsed;
}

export function getSupabasePublicUrl(): string {
  const value = Deno.env.get('SUPABASE_PUBLIC_URL') || Deno.env.get('SUPABASE_URL');

  if (!value) {
    throw new Error('SUPABASE_PUBLIC_URL/SUPABASE_URL is not configured');
  }

  const parsed = parseHttpUrl(value, 'Supabase public URL');

  if (parsed.username || parsed.password || parsed.search || parsed.hash) {
    throw new Error('Supabase public URL cannot contain credentials, a query, or a hash');
  }

  return `${parsed.origin}${parsed.pathname.replace(/\/+$/, '')}`;
}

/**
 * Replaces only the origin of a URL generated by the internal Supabase client.
 * The Storage path, query string (including signed tokens), and hash are kept
 * unchanged.
 */
export function withSupabasePublicOrigin(generatedUrl: string): string {
  const generated = parseHttpUrl(generatedUrl, 'Supabase-generated URL');
  const publicUrl = parseHttpUrl(getSupabasePublicUrl(), 'Supabase public URL');

  return `${publicUrl.origin}${generated.pathname}${generated.search}${generated.hash}`;
}
